Upgrades browser.
log:
The git source `git://github.com/network-for-good/konacha.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
error: could not lock config file .git/modules/chai-as-promised/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'chai-as-promised'
error: could not lock config file .git/modules/chai-backbone/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'chai-backbone'
error: could not lock config file .git/modules/chai-change/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'chai-change'
error: could not lock config file .git/modules/chai-changes/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'chai-changes'
error: could not lock config file .git/modules/chai-colors/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'chai-colors'
error: could not lock config file .git/modules/chai-datetime/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'chai-datetime'
error: could not lock config file .git/modules/chai-factories/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'chai-factories'
error: could not lock config file .git/modules/chai-fuzzy/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'chai-fuzzy'
error: could not lock config file .git/modules/chai-jq/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'chai-jq'
error: could not lock config file .git/modules/chai-jquery/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'chai-jquery'
error: could not lock config file .git/modules/chai-js-factories/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'chai-js-factories'
error: could not lock config file .git/modules/chai-json-schema/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'chai-json-schema'
error: could not lock config file .git/modules/chai-null/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'chai-null'
error: could not lock config file .git/modules/chai-param/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'chai-param'
error: could not lock config file .git/modules/chai-shallow-deep-equal/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'chai-shallow-deep-equal'
error: could not lock config file .git/modules/chai-spies/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'chai-spies'
error: could not lock config file .git/modules/chai-stats/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'chai-stats'
error: could not lock config file .git/modules/chai-string/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'chai-string'
error: could not lock config file .git/modules/chai-subset/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'chai-subset'
error: could not lock config file .git/modules/chai-things/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'chai-things'
error: could not lock config file .git/modules/chai-timers/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'chai-timers'
error: could not lock config file .git/modules/chai-xml/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'chai-xml'
error: could not lock config file .git/modules/js-factories/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'js-factories'
error: could not lock config file .git/modules/memo-is/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'memo-is'
error: could not lock config file .git/modules/mocha-as-promised/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'mocha-as-promised'
error: could not lock config file .git/modules/sinon/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'sinon'
error: could not lock config file .git/modules/sinon-chai/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'sinon-chai'
error: could not lock config file .git/modules/chai/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'chai'
error: could not lock config file .git/modules/mocha/config: No such file or directory
warning: Could not unset core.worktree setting in submodule 'mocha'
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....
Using rake 12.3.2
Using concurrent-ruby 1.1.4
Using i18n 0.9.5
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 4.2.11
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.4.0
Using nokogiri 1.10.4
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.9
Using crass 1.0.4
Using loofah 2.2.3
Using rails-html-sanitizer 1.0.4
Using actionview 4.2.11
Using rack 1.6.11
Using rack-test 0.6.3
Using actionpack 4.2.11
Using globalid 0.4.2
Using activejob 4.2.11
Using mini_mime 1.0.1
Using mail 2.7.1
Using actionmailer 4.2.11
Using activemodel 4.2.11
Using arel 6.0.4
Using activerecord 4.2.11
Using public_suffix 3.0.2
Using addressable 2.5.2
Using execjs 2.7.0
Using autoprefixer-rails 6.7.7.2
Using sass 3.4.23
Using bootstrap-sass 3.3.7
Using browser 2.7.1 (was 1.1.0)
Using bundler 1.17.3
Using byebug 9.0.6
Using xpath 2.1.0
Using capybara 2.18.0
Using launchy 2.4.3
Using capybara-screenshot 1.0.18
Fetching mime-types-data 3.2019.1009 (was 3.2018.0812)
Installing mime-types-data 3.2019.1009 (was 3.2018.0812)
Fetching mime-types 3.3 (was 3.2.2)
Installing mime-types 3.3 (was 3.2.2)
Using carrierwave 1.3.1
Using ffi 1.10.0
Using childprocess 0.6.3
Using coderay 1.1.1
Using coffee-script-source 1.12.2
Using coffee-script 2.4.1
Using colorize 0.8.1
Using database_cleaner 1.5.3
Fetching diff-lcs 1.2.5
Installing diff-lcs 1.2.5
Using ejs 1.1.1
Using factory_girl 4.5.0
Using thor 0.20.3
Using railties 4.2.11
Using factory_girl_rails 4.6.0
Using font-awesome-rails 4.7.0.5 (was 4.7.0.4)
Using temple 0.8.2 (was 0.8.0)
Using tilt 2.0.7
Using haml 5.1.2 (was 5.0.4)
Using jquery-rails 4.3.5 (was 4.3.3)
Using sprockets 3.7.2
Using sprockets-rails 3.2.1
Using konacha 4.0.0 from git://github.com/network-for-good/konacha.git (at master@cc2a061)
Using konacha-chai-matchers 1.0.1 from https://github.com/network-for-good/konacha-chai-matchers.git (at master@eb72a45)
Using metaclass 0.0.4
Using method_source 0.8.2
Using mocha 1.1.0
Using rails 4.2.11
Using rubyzip 1.2.2
Using roo 2.6.0
Using ruby-ole 1.2.12.2 (was 1.2.12.1)
Using spreadsheet 1.2.5 (was 1.1.9)
Using roo-xls 1.2.0
Using sass-rails 5.0.7
Using simple_form 4.0.0
Using nfg_csv_importer 0.1.1.0 from source at `.`
Using slop 3.6.0
Using pry 0.10.4
Using pry-byebug 3.4.2
Using puma 3.11.4
Using rspec-support 3.4.1
Using rspec-core 3.4.2
Using rspec-expectations 3.4.0
Using rspec-mocks 3.4.1
Using rspec-rails 3.4.2
Using rspec-rails-mocha 0.3.2
Using rspec_junit_formatter 0.4.1
Using websocket 1.2.4
Using selenium-webdriver 3.4.0
Using shoulda-matchers 3.1.1
Using sqlite3 1.3.11
Bundle complete! 18 Gemfile dependencies, 93 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.